### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by kajzersoze** [stievie/POAuth2#1]
I'm using Lazarus and I've compiled the POAuth2 demo app in laz directory.
Working fine, no issues.
However, I'm having some problems logging in to reddit's API via Oauth2.
I have all the data needed, created the app on reddit, all that works fine btw in python.

Tried different methods with your app and all I get are errors.

Anyway.. if you have used reddit successfully with this, maybe you can share what exactly do I need to set in Site and Grant Type.

**Comment by stievie** [comment]
Hm, yah, finally I got it working:

*Site* https://www.reddit.com/api/v1
*Grant Type* **User Credentials**
*Username* **Your Reddit user name**
*Password* **Your Reddit password**
*Client ID*, Client Secret* **leave blank**
*Tools -> Options -> HTTP Basic Authentication* Username, Password **Client ID** and **Client Secret** of registered Reddit app. This App must be of type *Script* (probably)

![clipboard03](https://cloud.githubusercontent.com/assets/900888/15109766/5f950f26-15dd-11e6-90d6-168e62e8bc57.png)

But there is a bug parsing the content-type header, so the response is not recognized as JSON. You can fix it by changing `uOAuth2Tools.IsJson()` to also accept `application/json; charset=UTF-8` as valid value.

**Comment by kajzersoze** [comment]
Yeah, getting : "Exception: JSON required, got application/json; charset=UTF-8"

I'll play with it a bit later, many thanks for finding the right steps !

**Comment by stievie** [comment]
I think there is another problem: Indiy still sends the Basic Auth Header for the resosuce requests, although it should send the access token instead. I'll have a look.

**Comment by kajzersoze** [comment]
Yes, just trying to figure that out, because in this simple python example it's working fine :
https://github.com/reddit/reddit/wiki/OAuth2-Quick-Start-Example

I get access token , expiry, type...
But if I slightly modify headers (User agent) it throws error.

**Comment by stievie** [comment]
Oh, now I see what could be the reason: You request the access token from https://www.reddit.com/ but you request the resource from https://oauth.reddit.com a different subdomain. Ok, not really a problem, but to support this, the program must be modified.

**Comment by stievie** [comment]
The last push fixes this issue (now i get a 404, and thats great!).

The config:
*Site* **https://oauth.reddit.com/api/v1**
*Tools -> Options -> Token endpoint* **https://www.reddit.com/api/v1** (Note the absolute URL now)

**Comment by kajzersoze** [comment]
I'm with you, keep going :+1:

**Comment by kajzersoze** [comment]
Thing I can't figure out is why we can't get access token, we can worry about using it later.
Just by using https://www.reddit.com/api/v1/access_token we should get something like this :
{u'access_token': u'fhTdafZI-0ClEzzYORfBSCR7x3M',
 u'expires_in': 3600,
 u'scope': u'*',
 u'token_type': u'bearer'}

**Comment by stievie** [comment]
Did you pull the last version? I can get an access token, but the resource call fails with `{"error": 403}`. What do you get instead?

**Comment by kajzersoze** [comment]
Yeah I did pull it, didn't know you actually got access token.
Well, I must be doing something wrong then.
I get error 404 and no access token.

**Comment by kajzersoze** [comment]
My app there is build as script, can't see where I'm making a mistake.
Can you please post your settings again, with this latest pull ?

**Comment by kajzersoze** [comment]
Mine :
Site : https://oauth.reddit.com/api/v1
Username : my reddit username
Password : my reddit password
Grant Type : User credentials

Resource is blank, as everything else.

In Tools->Options :
Token endpoint : https://www.reddit.com/api/v1
Username : App id
Password : App secret

**Comment by stievie** [comment]
Tools Options Token endpoint should be https://www.reddit.com/api/v1/access_token
Try as resource `/me` like in the example. The rest is the same.

**Comment by kajzersoze** [comment]
Right, I had it like that the first time, but then I tried few things and it left like that...
Anyway... I get "Exception: Server returned 403: {"error": 403}" and yeah indeed there's access token, but only in log, I thought it would be populated in the main form.
And I didn't even know about that log feature, so it was probably there even without latest commits.

**Comment by kajzersoze** [comment]
Anyway, is that token stored somewhere ?
Because, you know, that's why the error, we need to use that token for oauth sudomain part and Resources. Also, we had to utilize refresh token later, not a big problem to rewrite the whole thing, I mean write separate program for all of that, which I plan to do anyway, but need that access token sotred somehow.

**Comment by kajzersoze** [comment]
btw it also works without reddit username and password, with Client Credentials.
By that I mean access token is received.
Which is a correct way anyway, more secure.
There's still error 403
All that you fill in Tools->Options
App is designed that you have to put something in client ID and secret fields, but there's no need for it. with that method.

But.. no matter the method, header is the main problem why it isn't working.
It needs to be changed after we get access token :
headers = {"Authorization": "bearer fhTdafZI-0ClEzzYORfBSCR7x3M", "User-Agent": "ChangeMeClient/0.1 by YourUsername"}

And that's the main problem we have errors.

**Comment by kajzersoze** [comment]
Interesting problem, funny how this simple python script works : https://bpaste.net/show/86a6511e6aff

**Comment by kajzersoze** [comment]
Found what's the problem, it's Indy !

When I replaced Indy with Synapse it worked straight away.

**Comment by stievie** [comment]
Hm, this is strange, maybe the Lazarus Indy version has some bugs or is not up to date. Anyway, great that you found a solution.

**Comment by kajzersoze** [comment]
Probably, but you were getting 403 as well...
Anyway, all good now, thanks for all your help.

**Comment by stievie** [comment]
Yes, I get a 403 but only with Reddit. Even if I find the bug in Indy I can only fix my version. And the Indy client was only a sample client anyway. Maybe you can provide your Synapse client so I can add it as alternative to the Indy client.

**Comment by kajzersoze** [comment]
Sure, though when I said "replaced Indy with Synapse" I didn't mean I did that in your code, but in my testing code I wrote from scratch in order to see what exactly is going on.
Okay, so here's the quick and dirty unit showing just how Indy doesn't work and Synapse does :
https://bpaste.net/show/04b3772e9572

So, it's a hybrid and code from Synapse is used only in getapisynapse procedure.
getapi (using Indy) gets 403 while getapisynapse works.
Comment getapi and uncomment getapisynapse in Button1.click to see.
Just add button and memo on form, or reuse it as you wish, fill your reddit data in gettoken procedure.
I tried many different options for Indy btw, mainly SSL, nothing worked, I just couldn't do it and was out of ideas. Please do tell if you maybe figure it out.

I'll send pure Synapse code shortly.
