### ISSUE TITLE
Error not load SSL library.

### ISSUE THREAD

**Issue by xyberVI** [stievie/POAuth2#2]
When attempting to access an api, I get the following error: 

> EIdOSSLCouldNotLoadSSLLibrary:  Could not load SSL library.

**Comment by stievie** [comment]
If you are using HTTPS you need the OpenSSL libraries, see https://github.com/stievie/POAuth2#https

If you are on Windows put them (libeay32.dll and ssleay32.dll) into the program directory.

**Comment by stievie** [comment]
I guess that's solved.
